testname: webMUSHRA
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Сайн байна уу
      content: Танд энэ өдрийн мэнд хүргэе. Үнэлгээ хийж өгч байгаад баярлалаа.     
    - type: mushra
      id: trial_random_1
      name: Англи  + Монгол 15мин, 30мин, 60мин
      content: Эхний аргумент нь конвенцоор гүйцэтгэгдэж байгаа файлтай холбоотой файлын нэрийг зааж өгөх ёстой.
      enableLooping: true 
      reference: configs/resources/audio/GT/S11-MTG2.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/EN/30min/newGT_phoneme_11_gen.wav
          C2: configs/resources/audio/EN/15min/newGT_phoneme_11_gen.wav
          C3: configs/resources/audio/EN/1h/newGT_phoneme_11_gen.wav
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
